namespace Withywoods.Hubspot.Abstractions.Providers;

/// <summary>
/// Token provider.
/// </summary>
public interface ITokenProvider
{
    /// <summary>
    /// Authorization code generated by HubSpot while adding an application to a given user (OAuth).
    /// </summary>
    string AuthorizationCode { get; set; }

    /// <summary>
    /// Token generated by HubSpot, used as Bearer token in REST API calls.
    /// </summary>
    string Token { get; }
}
