# Azure pipeline definition for the integration of the solution (continuous integration)
# See: https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr:
  autoCancel: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

schedules:
- cron: "0 0 * * *"
  displayName: 'Daily midnight build'
  branches:
    include:
    - master
  always: true

variables:
# library variable groups
- group: 'build-tools'
# common task variables
- name: 'BuildConfiguration'
  value: 'Debug'
- name: 'SolutionFile'
  value: 'Withywoods.sln'
- name: 'TestProjects'
  value: 'test/*Tests/*.csproj'
- name: 'UnitTestProjects'
  value: 'test/*UnitTests/*.csproj'
- name: 'TestRunSettings'
  value: 'CodeCoverage.runsettings'
# tool variables (Sonar)
- name: 'sonar.project.name'
  value: 'Withywoods'
- name: 'sonar.project.key'
  value: 'withywoods'

# Unit testing
stages:
- stage: 'unit_testing'
  displayName: 'Unit testing'
  jobs:
  - job: 'linux_unittests'
    displayName: 'Unit tests run on Linux'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: $(dotnet.sdk.version.lts)
    - task: DotNetCoreCLI@2
      displayName: 'Build the .NET solution'
      inputs:
        command: 'build'
        projects: '$(SolutionFile)'
        arguments: '-c $(BuildConfiguration)'
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        COREHOST_TRACE: 0
    - task: DotNetCoreCLI@2
      displayName: 'Run the .NET unit tests'
      inputs:
        command: 'test'
        projects: '$(UnitTestProjects)'
        arguments: '--configuration $(BuildConfiguration)'
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        COREHOST_TRACE: 0
# Integration testing
- stage: 'integration_testing'
  displayName: 'Integration testing'
  dependsOn: [] # no dependencies: run at the same time as the unit testing stage
  jobs:
  - job: 'windows_integrationtests'
    displayName: 'Windows CI'
    pool:
      # code coverage generation only works on Windows for the moment
      vmImage: 'windows-latest'
    steps:
    - task: PowerShell@2
      displayName: 'Install locally MongoDB'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Installing latest MongoDB"
          choco install mongodb --version $(mongodb.version.lts)
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: $(dotnet.sdk.version.lts)
    - task: DotNetCoreCLI@2
      displayName: 'Restore .NET packages'
      inputs:
        command: 'restore'
        projects: '$(SolutionFile)'
        feedsToUse: 'select'
        noCache: $(dotnet.cache.disable)
    - task: PowerShell@2
      displayName: 'Start local MongoDB'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Starting MongoDB"
          $env:Path += ";$(windows.mongodb.path)"
          md log
          md data
          Start-Process -FilePath "mongod" -ArgumentList "--logpath log/mongod.log", "--dbpath data", "--port 27017" -WindowStyle Hidden
    - task: SonarCloudPrepare@1
      displayName: 'Prepare code analysis'
      inputs:
        SonarCloud: '$(sonar.instance)'
        organization: '$(sonar.organization)'
        scannerMode: 'MSBuild'
        projectKey: '$(sonar.project.key)'
        projectName: '$(sonar.project.name)'
        extraProperties: |
          sonar.cpd.exclusions=**/Models/*.cs,**/Dto/*.cs,samples/**/Program.cs
    - task: DotNetCoreCLI@2
      displayName: 'Build the .NET solution'
      inputs:
        command: 'build'
        projects: $(SolutionFile)
        arguments: '-c $(BuildConfiguration)'
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        COREHOST_TRACE: 0
    - task: DotNetCoreCLI@2
      displayName: 'Run all tests on .NET projects'
      inputs:
        command: 'test'
        projects: $(TestProjects)
        arguments: '--configuration $(BuildConfiguration) --settings $(System.DefaultWorkingDirectory)/$(TestRunSettings) --collect "Code coverage"'
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        COREHOST_TRACE: 0
    - task: SonarCloudAnalyze@1
      displayName: 'Analyze the code with Sonar'
    - task: SonarCloudPublish@1
      displayName: 'Publish the code analysis results'
      inputs:
        pollingTimeoutSec: '300'
    - task: PowerShell@2
      displayName: 'Stop local MongoDB'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Stopping MongoDB"
          Stop-Process -Name "mongod" -ErrorAction SilentlyContinue -Force
    - task: CopyFiles@2
      displayName: 'Copy screenshots'
      condition: failed()
      inputs:
        Contents: '**/screenshot*.png'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        flattenFolders: true
    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifacts'
      condition: failed()
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
