services:
  demoblazorwebapp:
    image: withywoods-demoblazorwebapp:local
    build:
      context: .
      dockerfile: samples/DemoBlazorWebApp/Dockerfile
    ports:
      - "9001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  demowebapi:
    image: withywoods-demowebapi:local
    build:
      context: .
      dockerfile: samples/DemoWebApi/Dockerfile
    ports:
      - "9002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
