name: CI
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# purpose: Continuous Integration pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      run-code-quality:
        description: 'Check code quality?'
        required: false
        type: boolean
        default: false

concurrency:
  group: "${{ github.ref }}-ci"
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  markup-lint:
    name: Markup
    uses: devpro/github-workflow-parts/.github/workflows/reusable-markup-lint.yml@c90ba46a93ca90123f57744b47e49c1a73962cea

  code-quality:
    name: Code
    if: github.event_name != 'workflow_dispatch' || inputs.run-code-quality
    uses: devpro/github-workflow-parts/.github/workflows/reusable-dotnet-quality.yml@c90ba46a93ca90123f57744b47e49c1a73962cea
    with:
      custom-commands: |
        dotnet build --no-restore --configuration Debug test/DemoBlazorWebApp.PlaywrightTests
        pwsh test/DemoBlazorWebApp.PlaywrightTests/bin/Debug/net10.0/playwright.ps1 install chromium
      dotnet-test-args: "--report-xunit-trx --coverage --coverage-output-format cobertura"
      fossa-enabled: true
      sonar-enabled: true
      sonar-organization: ${{ vars.SONAR_ORG }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      sonar-project-name: Withywoods
      workflow-parts-version: c90ba46a93ca90123f57744b47e49c1a73962cea
    secrets:
      fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
