name: CI
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# purpose: Continuous Integration pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      run-code-quality:
        description: 'Check code quality?'
        required: false
        type: boolean
        default: false

concurrency:
  group: "${{ github.ref }}-ci"
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  markup-lint:
    name: Markup
    uses: devpro/github-workflow-parts/.github/workflows/reusable-markup-lint.yml@e0707dae4fc9b3aae385c73edbb21c2cc5e1d4e4

  code-quality:
    name: Code
    if: github.event_name != 'workflow_dispatch' || inputs.run-code-quality
    uses: devpro/github-workflow-parts/.github/workflows/reusable-dotnet-quality.yml@e0707dae4fc9b3aae385c73edbb21c2cc5e1d4e4
    with:
      dotnet-test-args: "--report-xunit-trx --coverage --coverage-output-format cobertura"
      fossa-enabled: true
      sonar-enabled: true
      sonar-organization: ${{ vars.SONAR_ORG }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      sonar-project-name: Withywoods
      workflow-parts-version: e0707dae4fc9b3aae385c73edbb21c2cc5e1d4e4
    secrets:
      fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
