name: CI
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# purpose: Continuous Integration pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      run-code-quality:
        description: 'Check code quality?'
        required: false
        type: boolean
        default: false

concurrency:
  group: "${{ github.ref }}-ci"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  git-check:
    name: Git
    uses: ./.github/workflows/reusable-git-check.yml
    with:
      is-pull-request: ${{ github.event_name == 'pull_request' }}

  markup-lint:
    name: Markup
    uses: devpro/github-workflow-parts/.github/workflows/reusable-markup-lint.yml@0fb84dd26bcb614ca4683c8e501008fccf424d51

  code-quality:
    name: Code
    needs: git-check
    if: needs.git-check.outputs.app_changed == 'true' || (github.event_name == 'workflow_dispatch' && inputs.run-code-quality)
    uses: devpro/github-workflow-parts/.github/workflows/reusable-dotnet-quality.yml@0fb84dd26bcb614ca4683c8e501008fccf424d51
    with:
      custom-commands: |
        dotnet build --no-restore --configuration Debug test/DemoBlazorWebApp.PlaywrightTests
        pwsh test/DemoBlazorWebApp.PlaywrightTests/bin/Debug/net10.0/playwright.ps1 install chromium
      dotnet-test-args: "--report-xunit-trx --coverage --coverage-output-format cobertura"
      fossa-enabled: true
      sonar-enabled: true
      sonar-organization: ${{ vars.SONAR_ORG }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      sonar-project-name: Withywoods
      workflow-parts-version: 0fb84dd26bcb614ca4683c8e501008fccf424d51
    secrets:
      fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
