name: PKG
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# purpose: Continuous Delivery (aka Packaging & Shipping)

on:
  push:
    branches:
      - main
    paths:
      - 'Directory.Build.props'
  workflow_dispatch:
    inputs:
      push-enabled:
        description: 'Push packages?'
        required: false
        type: boolean
        default: false

jobs:
  package-publication:
    name: Package / Publication
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Checkout workflow parts
        uses: actions/checkout@v6
        with:
          repository: devpro/github-workflow-parts
          ref: 79ef8b68e376c0cb3df0fc82e25961cc649023db
          path: workflow-parts
      - name: Pack & push .NET projects
        uses: ./workflow-parts/actions/dotnet/pack-push
        with:
          registry-token: ${{ secrets.NUGET_API_KEY }}
          push-enabled: ${{ github.event_name != 'workflow_dispatch' || inputs.push-enabled }}
