name: PKG
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# purpose: Continuous Delivery (aka Packaging & Shipping)

on:
  push:
    branches:
      - main
    paths:
      - 'Directory.Build.props'
  workflow_dispatch:
    inputs:
      push-enabled:
        description: 'Push packages?'
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  git-check:
    name: Git
    uses: ./.github/workflows/reusable-git-check.yml

  package-publication:
    name: Package / Publication
    needs: git-check
    if: github.event_name == 'workflow_dispatch' || needs.git-check.outputs.app_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Checkout workflow parts
        uses: actions/checkout@v6
        with:
          repository: devpro/github-workflow-parts
          ref: 0fb84dd26bcb614ca4683c8e501008fccf424d51
          path: workflow-parts
      - name: Pack & push .NET projects
        uses: ./workflow-parts/actions/dotnet/pack-push
        with:
          registry-token: ${{ secrets.NUGET_API_KEY }}
          push-enabled: ${{ github.event_name != 'workflow_dispatch' || inputs.push-enabled }}
